seed: 1
cuda: 0

env:
  env_name: AntFH-v0
  T: 1000

reward:
  pretrained: logs/AntFH-v0/exp-16/airl_imitation/3/model/reward_model_itr820_det5680_sto5719.pkl

# 对齐 airl_seals_ant_best_hp_eval.json
ppo:
  n_steps: 8192
  batch_size: 16
  n_epochs: 10
  learning_rate: 3.249429831179079e-5
  clip_range: 0.3
  ent_coef: 3.27750078482474e-6
  gae_lambda: 0.8
  gamma: 0.995
  max_grad_norm: 0.9
  vf_coef: 0.4351450387648799

total_timesteps: 10000000
eval_interval: 8192
n_eval_episodes: 10
